-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 14:27:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_ExerciseLooper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_ExerciseLooper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ExerciseLooper` DEFAULT CHARACTER SET utf8 ;
USE `db_ExerciseLooper` ;

-- -----------------------------------------------------
-- Table `db_ExerciseLooper`.`t_exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ExerciseLooper`.`t_exercises` (
  `id_exercises` INT NOT NULL AUTO_INCREMENT,
  `exe_title` VARCHAR(100) NULL,
  `exe_state` ENUM('building', 'answering', 'closed') NULL,
  PRIMARY KEY (`id_exercises`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ExerciseLooper`.`t_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ExerciseLooper`.`t_questions` (
  `id_questions` INT NOT NULL AUTO_INCREMENT,
  `que_label` VARCHAR(1000) NOT NULL,
  `que_value_kind` VARCHAR(100) NOT NULL,
  `id_exercises` INT NOT NULL,
  PRIMARY KEY (`id_questions`),
  INDEX `fk_t_questions_t_exercises_idx` (`id_exercises` ASC) VISIBLE,
  CONSTRAINT `fk_t_questions_t_exercises`
    FOREIGN KEY (`id_exercises`)
    REFERENCES `db_ExerciseLooper`.`t_exercises` (`id_exercises`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_ExerciseLooper`.`t_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_ExerciseLooper`.`t_responses` (
  `id_responses` INT NOT NULL AUTO_INCREMENT,
  `res_text` VARCHAR(1000) NULL,
  `res_datetime` DATETIME NULL,
  `id_questions` INT NOT NULL,
  PRIMARY KEY (`id_responses`),
  INDEX `fk_t_responses_t_questions1_idx` (`id_questions` ASC) VISIBLE,
  CONSTRAINT `fk_t_responses_t_questions1`
    FOREIGN KEY (`id_questions`)
    REFERENCES `db_ExerciseLooper`.`t_questions` (`id_questions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
